# Generated by Django 5.0.1 on 2024-02-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_author_book_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='category',
        ),
    ]
