# Generated by Django 5.0.1 on 2024-02-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='product',
        ),
    ]
