# Generated by Django 5.0.1 on 2024-02-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='book',
        ),
    ]
