# Generated by Django 5.0.1 on 2024-02-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='custom',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
